surge-synthesizer/OB-Xf

.github/workflows/build-plugin.yml
CMakeLists.txt
cmake/basic_installer.cmake

No release installer yet. One step at a time

Set up PR-level CI.

---

.github/workflows/build-plugin.yml
CMakeLists.txt

so you can set it up in your IDE or what not

Add a cmake option for COPY_PLUGIN_AFTER_BUILD

---

CMakeLists.txt

Remove explicit Clang optimization and architecture flags; 

---

Source/PluginEditor.cpp
Source/PluginEditor.h
assets/Surge Synth Team/OB-Xf/Themes/QuickAndDirtyGREC/coords.xml

Closes #27
Requires updating coords.xml file locally!

Keytrack is now a knob!

---

Source/PluginEditor.cpp

PWOsc2Ofs default val 0.f

---

Source/Core/Constants.h
Source/Engine/Motherboard.h
Source/Engine/SynthEngine.h
Source/PluginEditor.cpp
Source/State/StateManager.cpp

Moved out MAX_VOICES and MAX_PANNINGS to Constants.h

Split voices context menu into 4 columns

---

.gitattributes
Source/Engine/AdsrEnvelope.h
Source/Parameter/FreeLayoutHelper.h

Add gitattributes and specify *.h files as C++ (fixes #20)

ADSR tooltips (not very correct)

---

Source/Gui/Knob.h
Source/PluginEditor.cpp

Use Shift for finetune and Ctrl for quantize

---

src/PluginEditor.cpp
src/Utils.cpp
src/Utils.h
src/engine/Params.h
src/gui/ButtonList.h

Remove dialog when initializing preset
Rename deletePreset() to initializePreset()

Fix the ButtonList floating point round trip

---

CMakeLists.txt
src/PluginEditor.cpp
src/PluginEditor.h
src/gui/AboutComponent.h
src/gui/AboutScreen.h

based on @baconpaul's elfin controller about screen.

Added about screen

---

src/components/SetPresetNameWindow.cpp
src/components/SetPresetNameWindow.h

yup ok/cancel = enter/esc
Closes #69 (nice)

Ok/Cancel now responds to enter/esc

---

src/PluginEditor.cpp
src/PluginEditor.h

resize via the menu

---

CMakeLists.txt
src/Utils.h
src/core/Constants.h
src/engine/AdsrEnvelope.h
src/engine/AudioUtils.h
src/engine/Filter.h
src/engine/Lfo.h
src/engine/ObxfVoice.h

Used fastmath approximation for sine LFO
Renamed TPT lowpass filter methods in AudioUtils
Refactored AdsrEnvelope with State enum instead of magic number integers for tracking envelope state

Added calc for triangle and saw to LFO

---

README.md
assets/Surge Synth Team/OB-Xf/Themes/QuickAndDirtyGREC/coords.xml
src/gui/Knob.h
src/parameter/FreeLayoutHelper.h
src/parameter/ParameterAdaptor.h
src/parameter/SynthParam.h

Addresses #113 
- Use basic blocks for all params
- remove old layout code that's not used anymore
- small fix to coords file for oversamplingButton

Update rest of parameters to use sst basic blocks

---

src/parameter/ParameterAdaptor.h

Normalise step when setting engine value

Fix: negative values now restoring

---

src/PluginEditor.cpp
src/PluginEditor.h

Safety net if themes aren't located

---

src/PluginProcessor.cpp
src/PluginProcessor.h
src/gui/Knob.h

randomise all pans and reset all pans to default via context menu

---

src/PluginProcessor.cpp
src/PluginProcessor.h
src/gui/Knob.h

change spelling of 'randomise' to American English 'randomize'

randomize not randomise

---

assets/Surge Synth Team/OB-Xf/Themes/Default/coords.xml
src/PluginEditor.cpp
src/PluginEditor.h

Changed the tags to more logical names and lowercase
Added "pic" argument so that different widgets can point to different assets (defaulting to currently used filenames, if not found)

Update the skin XML file

---

assets/Surge Synth Team/OB-Xf/Themes/Default/coords.xml
src/PluginEditor.cpp
src/PluginEditor.h
src/parameter/ParameterAdaptor.h

Documented the XML arguments in the coords file
LFO waveform knobs have a custom value readout similar to voice variation pan knobs
Reduced decimal places from 2 to 1 for many parameters

Sliders are working!

---

src/engine/Motherboard.h
src/engine/SynthEngine.h

Basically rename variables and add sopme comments so its clearer how the VM works. Most importantly "VMA" is latest- vs lowest- priority mode

A comment-and-rename-only change to the voice manager

---

src/PluginProcessor.cpp

1. The randomize value needed to be normalized
2. While doing that, smidge i a bit towards a zero-prefering distro
3. And add begin/end gestures

Fix a couple of randomize pan problems

---

src/engine/Motherboard.h
src/engine/SynthEngine.h

In anticipation of multiple priority modes, make an enum in Motherboard.h which is set and used. If you set it to highest right now you just get latest.

More voice manager: Priority as an Enum

---

src/engine/Motherboard.h
src/engine/SynthEngine.h
src/engine/Voice.h
src/engine/VoiceQueue.h
src/midi/MidiHandler.cpp

Re-implement the voice manager to allow 
If poly == voices and unison on it is exactly the old unison mode
If poly != 1 and unison off it is exaclty the old non-unison mode
If poly != 1 and voices != 1 and unison is on, then it does the new poly unison following stealing rules

Poly unison vm

---

src/PluginEditor.cpp
src/PluginEditor.h
src/engine/Voice.h

In order to fix sawtooth behaving like a ramp (no bueno)

Invert LFO value for Volume destination

---

src/PluginProcessor.cpp
src/PluginProcessor.h
src/engine/Bank.h
src/parameter/ParameterAdaptor.h
src/state/StateManager.cpp

- Fixed some state restoration bugs
- Default values are correct
- Updated some patches code and added some helpers to the bank class
TODO: 
- Further updates to patches
- still a restore from state bug where pans are slightly right due to some extra normalise step (but at-least the ui is correct)
- First patch is now always wrong again
- cycling through patches with the buttons causes all pans to be panned right (normalise bug)

further state and patch updates

---

scripts/fix_file_comments.pl
scripts/fix_header_guards.pl
src/PluginEditor.cpp
src/PluginEditor.h
src/PluginProcessor.cpp
src/PluginProcessor.h
src/components/Constrainer.h
src/components/ScalableComponent.h
src/gui/ImageMenu.h
src/midi/MidiHandler.cpp
src/midi/MidiHandler.h
src/parameter/ParameterAdapter.h
src/parameter/ParameterAttachment.h
src/parameter/ParameterList.h
src/parameter/ValueAttachment.h

- Adaptor to Adapter
- Header guards updated
- Make getter methods less verbose
- Update scripts to `src` not `Source`

general tidy up

---

src/state/StateManager.cpp

parameters and correct patch now restore again.

fix state restoration

---

src/PluginEditor.cpp
src/core/Constants.h
src/engine/AdsrEnvelope.h
src/engine/AudioUtils.h
src/engine/DelayLine.h
src/engine/Motherboard.h
src/engine/SynthEngine.h
src/engine/Voice.h
src/gui/Knob.h
src/parameter/ParameterList.h

Only show the exact amount of LEDs as we have set the polyphony
Add param attachment to ButtonList (should help in moving those to asInt() via PMD)
Process toggleAttachments in updateFromHost()

Quite a number of variable renames for clarity

---

src/engine/Filter.h
src/engine/SynthEngine.h
src/engine/Voice.h

I got a fever, and the only prescription.. is more structs!

Refactor Filter.h

---

src/PluginEditor.cpp
src/PluginEditor.h
src/engine/Smoother.h

- Refactor `loadTheme()` function into multiple functions
- cache the xml to avoid re-parsing in `resized()`
- replace `juce::OwnedArray` with `std::vector<std::unique_ptr>`
Addresses #210

Editor refactor

---

src/PluginEditor.cpp
src/PluginEditor.h
src/Utils.cpp
src/Utils.h
src/engine/Smoother.h

- Replace instances of `juce::Array` with `std::vector` in the editor
- Replace calls to `push_back` with `emplace_back` mostly
- removed unused function parameters passing the processor when not needed

Further editor refactoring

---

src/engine/AdsrEnvelope.h
src/engine/BlepData.h
src/engine/Filter.h
src/engine/Noise.h
src/engine/OscillatorBlock.h
src/engine/PulseOsc.h
src/engine/SawOsc.h
src/engine/SynthEngine.h
src/engine/TriangleOsc.h
src/engine/Voice.h

Rihanna would sing "structs structs structs structs structs structs structs" :D
Also made the Param/Parameter structs consistently named "Parameters"
Document the getters in Noise.h

Refactor OscillatorBlock and saw/pulse/triangle generators

---

src/engine/Motherboard.h
src/engine/Voice.h

THe voice stealer had bugs which I hadn't caught since I just tested it with short envelopes.

Fix stuck note cases

---

src/PluginEditor.cpp
src/PluginProcessor.cpp
src/PluginProcessor.h
src/gui/ButtonList.h
src/gui/ImageMenu.h
src/gui/Label.h
src/gui/MultiStateButton.h
src/gui/ToggleButton.h
src/midi/MidiHandler.cpp
src/parameter/ParameterAdapter.h

- remove unused processor reference from components
- remove old not needed queue calls
-  move pan context actions into paramadaptor to avoid listener bugs:

general code cleanup

---

src/PluginEditor.cpp
src/PluginEditor.h

A clearer user facing missing assets message

---

src/engine/Filter.h
src/engine/Voice.h

Reset the filter on HQ toggle also

---

resources/NightlyBlurb.md
src/engine/Motherboard.h
src/engine/SynthEngine.h

Going from big pop to tiny pop

AllSoundsOff when HQ toggles

---

CMakeLists.txt
src/Utils.cpp
src/Utils.h
src/gui/AboutScreen.h

1. Add filesystem and path support from plugin infra
2. Use it to set an unused factory path
3. Add to/from juce file and fs path which should work
4. Add copy to clipboard option on about screen

Add filesystem and path support from plugin infra

---

src/PluginEditor.cpp
src/PluginEditor.h

when selecting a zoom level twice it would zoom again

fix for scaling bug when clicking a zoom level twice

---

src/PluginEditor.cpp

- safe this everywhere
- call resized in loadtheme
- clear lfo controls list when changing theme (this was the reason for the crash)

Fix changing theme crash, capture safe pointer everywhere

---

src/gui/AboutScreen.h

Making the system info look closer to how it looks in Surge etc.

Small tweaks to About screen

---

src/PluginEditor.cpp
src/PluginEditor.h
src/components/ScalingImageCache.cpp
src/components/ScalingImageCache.h

if background.png is missing and background.svg is there etc...

Allow SVG for background in a skin

---

src/gui/ToggleButton.h

Demonstrates how to do an SVG conversion of a filmnstrip asset

Buttons can be SVG now

---

src/gui/ToggleButton.h

Fix a divide by zero which crashed windows release

---

src/gui/ToggleButton.h

where i had order of ops wrong for scaling

Fix a problem with toggle button due to svg port

---

src/PluginEditor.cpp
src/PluginEditor.h
src/gui/AboutScreen.h

About screen scales with zoom

---

src/PluginEditor.cpp
src/gui/Display.h

Closes #267
Gives a hint on how to do #266 also

Patch name display foolows zoom

---

src/PluginEditor.cpp
src/Utils.cpp
src/gui/AboutScreen.h

which is way more forgiving on Linux
Closes #233

Use pluginfra path for documents folder

---

src/PluginEditor.cpp
src/PluginEditor.h
src/Utils.cpp
src/Utils.h

An option to define a default zoom

---

src/engine/AdsrEnvelope.h

After much gnashing of teeth and doing of math, figure out the equivalence.
Closes #120

Add lin/log attack curve

---

CMakeLists.txt
src/gui/AboutScreen.h

Also fix the incorrect icon being used for the app

Show executable path in About screen

---

src/gui/Display.h

basically we run right against the margin and we blammo

Fix a display edge case which could ... display names

---

src/Utils.cpp
src/Utils.h

When you save a bank the checkmark wasnt right because utils had two places it stored the current bank and no consistency mechanism. Resolve before fighting bigger bank issues

Consistent current bank

---

src/PluginProcessor.cpp
src/PluginProcessor.h
src/engine/Bank.h
src/state/StateManager.cpp

While debugging the bank clobber issue I renamed things with better names at least so the code is more comprehensible. merge that

Name change only

---

CMakeLists.txt
cmake/get_dependencies.cmake
src/PluginEditor.cpp
src/PluginEditor.h
src/gui/FocusOrder.h
src/gui/Knob.h

Pretty close on accesibility but this makes us closer
1. Allow the jucegui focus debugger
2. Set an explicit tab order on a bunch of things
Addresses #39

Start of accesibility: Some tab order work

---

src/PluginEditor.cpp
src/PluginEditor.h

Also remove UI refresh of patch number menu, just do it in needNotifyToHost branch
Probably fixes #337?

Update host when changing patches in more places

---

src/PluginEditor.cpp
src/gui/MultiStateButton.h

Tab order getting better since multibutton no longer makes the specious unused text editor

More accesibility work

---

src/gui/Knob.h

Keybindings for knob min max default and show popup in place
Closes #39

Finalize accesibility

---

src/PluginEditor.cpp

Fix drag direction in vector horiz sliders

---

src/PluginEditor.cpp
src/parameter/ParameterAdapter.h

Random goes to a corrected "A_BIT_MORE" always and we dont show the menu (but preserve it ifdefed out)

A bit safer random

---

src/gui/AboutScreen.h

Add a small about tooltip to the icons

---

src/parameter/ParameterAdapter.h

1. The exlicded int list was ignored. Sign
2. Add poly to the excluded int list

Fix two rand issues

---

src/PluginEditor.cpp
src/gui/AboutScreen.h
src/gui/ButtonList.h
src/gui/Knob.h
src/gui/MultiStateButton.h
src/gui/ToggleButton.h
src/midi/MidiHandler.cpp
src/parameter/ParameterAdapter.h

Implement MIDI learn for MultiStateButton

---

src/gui/AboutScreen.h
src/gui/ButtonList.h

Also a minor typo tweak on About screen

Make ButtonList always show the full preset list if it fits on screen

---

src/PluginEditor.cpp
src/midi/MidiHandler.cpp
src/midi/MidiHandler.h
src/parameter/ParameterAdapter.h
src/state/StateManager.cpp
src/state/StateManager.h

Remove the current-session.xml hack from two-ago commit and instead put the midi mapping in the daw extra state so it saves per instance in your session

Move MIDI maping from current-session.xml to DES

---

src/PluginEditor.cpp
src/PluginEditor.h
src/gui/AboutScreen.h

Also fix the constrainer to always have lowest zoom level as minimum instead of hardcoded 50%.
Remove Display Scaling line from About page.

Add more zoom levels, gray out those too large for current display

---

src/state/StateManager.cpp
src/state/StateManager.h

Because that's where it belongs.
Also remove currentProgram from the bank format. Because we don't need to store it really.

Move selectedLFOIndex to DAWExtraState

---

src/PluginEditor.cpp
src/Utils.h
src/gui/AboutScreen.h

Also fix hitting assert in juce::File on Windows because of embedded theme path

Match About page link colors/behavior to Surge XT

---

src/PluginEditor.cpp
src/PluginProcessor.cpp
src/Utils.cpp
src/Utils.h
src/gui/ToggleButton.h
src/state/StateManager.cpp
src/state/StateManager.h

Fixes #447
Also implement exporting individual patches from currently selected group (right click on Group button)
Some Utils/StateManager cleanups and refactors

Fix copy via main menu not working
