surge-synthesizer/OB-Xf

- CMakeLists.txt
- Source/PluginEditor.cpp
- Source/Utils.cpp
- Replaced modal dialogs with async/non-blocking versions.
- Fixed to use the provided name instead of always Default when creating a new preset via the menu
I based this on some of the code from https://github.com/rfawcett160/OB-Xd-GREC @rfawcett160 but had to change a few things to get it to work (Export presets and banks was not working).
> feature: remove modal loops

- src/gui/Knob.h
- src/parameter/FreeLayoutHelper.h
- src/parameter/SynthParam.h
Basically make an AudioParameterFloat subclass containing an sst-basic-blocks ParamMetadata and then start adjusting code.
Addresses #113
> Add an ObxfParameterFloat which contains a metadata

- scripts/attacksim.py
- src/engine/AdsrEnvelope.h
The attack time, with its 0.9 peak and coeffients set to a 1.0 overshoot. didn't match the display time. This fixes it by adjusting the attack time in the coefficient appropriately.
And also stable under modulation
Addresses #116
Still need to check release and decay same way
And still need to move to basic blocks metadat
> Make attack time basically match the display

- src/parameter/FreeLayoutHelper.h
- src/parameter/ParameterAdaptor.h
- src/parameter/ParameterInfo.h
- src/parameter/SynthParam.h
1. Do ecomode
2. Modify ParameterInfo so that the meta is no longer optional
3. Remove other ParameterInfo constructors and members
4. Put the parameter index into the ObxfParameterFLoat
> Param Metadata Wrapup

- src/parameter/ParameterManager.cpp
new normalize step added to updateParameters. This allows pluginval to pass, previously none normalised values could be passed to the engine.
> Further parameter bug fixes

- src/engine/PulseOsc.h
- src/engine/SawOsc.h
- src/engine/TriangleOsc.h
Rarely when running the VST3 in pluginval we could get NaNs in the buffer caused by out-of-bounds access here, this update should prevent that.
> Clamp BLEP mixing to prevent out-of-bounds access and NaNs in buffer

- src/PluginEditor.cpp
remove the call to sendChangeMessage()
> fix clear button no longer resets all parameter values

- src/PluginEditor.cpp
- src/PluginEditor.h
to avoid an occasional crash on exit with a selected item due to destruction re-ordering
> Make melatonin insepctor a unique_ptr

- src/PluginProcessor.cpp
- src/PluginProcessor.h
this fixes both loading and initialising progs.
TODO:
- when loading from state parameters with values -1 to 1 increment. 
- this is a normalising issue in the state manager to fix
> fix programs having wrong values

- CMakeLists.txt
The PROJECT_VERSION was 0.8 but this changes it to 0.(year-2025+5).(day-of-year+1) meaning we get a new version each day.
This is particularly useful for macos users where the au hosting service uses version number advances to trigger rescans and the like properly.
But also is just a useful practice from SC borrowed here.
Obvioiusly when we ship 1.0 go to manual version numbers again
> Make the PROJECT_VERSION advance with date

- src/engine/Decimator.h
- src/engine/Motherboard.h
Otherwise we may get bad clicks, nans, etc...
> Reset decimator on oversample toggle

- src/engine/Lfo.h
- src/engine/Voice.h
Previously, we could go above unity gain with inverted modulation, now we just invert the waveform (which is how it should have been).
Also modified the LFO so that it is high first then low (it was inverted until now), this matches the icon on the GUI
> Improve behavior of LFO to volume modulation

- src/engine/Motherboard.h
- src/engine/SynthEngine.h
This fixes the issue where renders sounded an octave higher if HQ button was enabled. The cause was a SR mismatch because JUCE's prepareToPlay sent us host's SR (say 48k), this propagated throughout the synth, but HQ stuff was not being executed because Motherboard::SetHQ() was guarded by an early return if incoming value was the same as the `oversample` member.
Added a force argument to Motherboard::SetHQ() which is then only called from Motherboard::setSampleRate().
Fixes #269!
> Force execute SetHQ() when calling Motherboard::setSampleRate()

- src/PluginEditor.cpp
- src/components/ScalingImageCache.cpp
- src/components/ScalingImageCache.h
- src/gui/Knob.h
1. Update the ImageCache so that it has an SVG branch
- If foo.png isn't there and foo.svg is then isSVG("foo") will return true and so forth
- if foo_layer1.svg foo_layer2.svg is there the the layer count mechanism kicks in
2. Modify the knob class to be either one layer and rotate it or multiple layers as non-rot base, rot mid optional non-rot top as 1/2/3
3. FIx a problem in skin swapping that the image cache didn't reset correctly.
> Towards SVG Skins; an SVG Knob

- src/PluginEditor.cpp
- src/PluginEditor.h
- src/Utils.cpp
- src/Utils.h
- src/components/ScalingImageCache.cpp
Allow themes to come from both factory and user directories. Store the directory type and name in config
Use a data structure rather than a raw juce::File to represent a theme If the theme is non-configurable and some were found pick the first which closes #299
but this generally is the path towards #7
> Add support for multiple theme locations

- src/gui/Knob.h
- src/parameter/ParameterList.h
- src/parameter/SynthParam.h
1. Floats normalize elsewhere so the scale was wrong. Like OSC1 pitch shoed in bitwig as -1000 ... 10000 semitones
2. So normalize in knob not in the param to meet api spec
3. And add formatting methods for loads of params
4. And warn on the ones which don't have them
Closes #305
> Generally fix up the param-to-string normalization errors

- src/PluginEditor.cpp
- src/Utils.cpp
- src/Utils.h
- src/utilities/KeyCommandHandler.h
With the application support etc... storing of themes we dont necessarily have a user documents directory to start the synth which is fine until you go to save an fxp or set a setting.
So this change does a couple of things
1. Creates the user directory on startup if not there
2. Makes export patch use file chooser with the patch name
3. Adds an Open user Directory file menu item so you can get there
> Some changes to user dir and save patch

- .github/workflows/build-plugin.yml
We switched from BMP to PNG for our windows installer wizard image. This requires Inno Setup 6.5.2, but the runner has 6.4.0 installed and this was not documented. This makes sure we have the correct version.
> Install Inno Setup in pipeline

- cmake/get_dependencies.cmake
Windows installer recommends per-user install, which will cause support issues for DAWs that don't support it, DAWs that don't allow adding a plugin path, or just any user expecting it in system directory. Disabling this for now, if we ever re-introduce this we probably want a separate installer
> Inno Setup: Remove non-elevated install until DAWs catch up

- src/PluginEditor.cpp
- src/gui/MultiStateButton.h
- src/parameter/ParameterList.h
1. Multistate Button reads the value with the stringtovalue correctly if a parameter is present
2. The Tristate LFO buttons have a correct param metadata for conversion etc...
> More Accesible Fixes

- src/PluginEditor.cpp
- src/PluginEditor.h
- src/Utils.h
- src/components/ScalingImageCache.cpp
- src/components/ScalingImageCache.h
- src/gui/AboutScreen.h
This uses the plugin scale as well in the image cache load calculations It should fix a divergence between teh Standalone image selection and the vst3 on windows HDPI.
Windows HDPI is not fun.
> Diagnose (for sure) or fix (maybe) a windows fuzzy problem

- src/PluginEditor.cpp
- src/PluginProcessor.cpp
- src/PluginProcessor.h
updateHostDisplay by default udpates everything - latency param names and values programs and so on. We were calling it willy nilly with the default. This over-stressed all daws but in Logic it meant the setCurrentProgram order of operations would cause a rescan of params without them having been host updated and that would reset the entire thing wrongly. Bad bad.
So change it so that doesn't happen and low logic works great!
Addresses #333
> Be more parsimonious in our use of updateHostDisplay

- src/gui/Label.h
so ceil vs round. Stops truncation on vector label assets
> ClipRect for Label Traversal always outside

- src/PluginEditor.cpp
- src/PluginEditor.h
- src/gui/ButtonList.h
- src/gui/HasScaleFactor.h
- src/gui/ImageMenu.h
- src/gui/Knob.h
- src/gui/Label.h
- src/gui/MultiStateButton.h
- src/gui/ToggleButton.h
Initial zoom of non-100% didn't really work and I had the odd delayed resized call in the idle loop to work around it. Well I found out the problem. Basically
1. Want to force a call to scaleFactorChanged and
2. Label was screwed up generlally
Fix 1 by adding a HasScaleFactor interface we can cast to to force post resize in constructor
Fix 2 by moving Label for a Drawable to a Component. There was no need for it to ever implement the Drawable API.
> Fix some initial zoom problems

- src/midi/MidiHandler.cpp
- src/midi/MidiHandler.h
Now you can switch between patches 1-128 and 129-256!
TODO: Patch number display doesn't update on receiving Program Change.
Also disallow using CCs 0, 64, 74, 120 and 123 for MIDI learn.
> Implement CC #0 (Bank Select MSB) to work with Program Change

- resources/NightlyBlurb.md
- src/PluginEditor.cpp
- src/PluginEditor.h
- src/Utils.h
Windows HDPI plugin support is causing crashes and we dont know why. To keep the beta going, turn it off while we debug and update the Nightly Blurb to say so
> Temporarily turn off windows HDPI plugin support

- src/PluginProcessor.cpp
- src/engine/MidiMap.h
- src/midi/MidiHandler.cpp
- src/midi/MidiHandler.h
- src/parameter/ParameterManager.cpp
- src/parameter/ParameterManager.h
This completes the overhaul of how we apply midiCC at learn points. It does a few things
1. It adds a linear interp and makes it way closer to sample accurate as a result to smooth the inbound midi.
2. It adds a concept of "per target transform" in midicc
3. It adds the following transforms
- Regular
- Bipolar symmetric: 0,1 collapse to a same value, 64 to mid
- Pitch: basically if applied to pitch then 16 ... 110 maps to semis
- Stepped: Makes sure we use uniform step size midi space for integer params
Lots of testing to do here, but a good checkpoint
> MidiCC Application Overhaul; Lags and Transforms

- src/engine/Parameters.h
- src/engine/SynthEngine.h
The init patch seemed to have the LFO activated. There were two reasons for this
1. The clever '0/0.5/1 to 0/1/-1' didn't work if the value input was not exactly those. So things like vst3 mod and so forth would blow up this strategy. Fix with a round.
2. The sst-basic-blocks normalize value on an int used by default the silly surge convention of +0.05 and *0.9 so the inir value of LFO1ToPitch was 0 (int) but 0.05 (float normalized). Which combined with above bug went blammo. Fix this by making basic blocks have an off-by-default argument to use the crappy surge normalization, since we dont use it in surge.
Closes #425
> Fix two problems mis-activating LFO on Init

- CMakeLists.txt
- src/PluginEditor.cpp
- src/PluginProcessor.cpp
- src/PluginProcessor.h
- src/engine/Bank.h
- src/engine/Program.h
- src/engine/SynthEngine.h
- src/parameter/ParameterAdapter.cpp
- src/parameter/ParameterAdapter.h
- src/parameter/ParameterManager.cpp
- src/parameter/ParameterManager.h
- src/state/StateManager.cpp
Addresses #428
This commit basically adds a program double buffer and detects when the program is changed so we can 'restore' to factory on a per patch basis. Its an incomplete implementation of #428 but I'm merging it so we can test this step zero workflow.
Still to do include
- save all to original
- bank export undirties
- daw save undirties
- testing
> Patch Bank Restore/Save gestures

- src/PluginProcessor.cpp
- src/engine/Bank.h
- src/state/StateManager.cpp
When you save state, rather than assuming front->back in the patch store, we instead stream that dirty state and the back patch along with it. This means that a stream doesn't change your workflow and you pick up where you left off.
> Stream DirtyState and BackPatch to state information

- src/PluginEditor.cpp
- src/gui/MultiStateButton.h
- src/gui/ToggleButton.h
This will allow us to use context menu on buttons down the line if we wanted it (for consistency with knobs, we have the same in Surge XT).
Also, make it so that Ctrl/Cmd+clicking the 16 patch switching buttons will behave inverse to the state of the Group button.
> Replace RMB on LFO target buttons with Ctrl/Cmd+click

- src/PluginEditor.cpp
- src/PluginProcessor.cpp
- src/PluginProcessor.h
- src/Utils.cpp
- src/Utils.h
- src/engine/Bank.h
- src/gui/ToggleButton.h
- src/parameter/ParameterList.h
- src/state/StateManager.cpp
- src/state/StateManager.h
Closes #443
Also:
- Added Ctrl and Alt drag to Env To Pitch knob
- Transpose knob now only shows integer values (no decimals), because it's always quantized anyways
- Alt+drag on Osc 1/2 Pitch and Env To Pitch knobs was modified to snap to fourths and fifths, in addition to already snapping to octaves
> Add copy-paste options to patch 1-16 buttons
